name: app_law_order
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.6
  dio: ^5.4.0
  fluttertoast: ^8.2.4
  json_annotation: ^4.8.1
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  datetime_picker_formfield_new: ^2.1.0
  intl: ^0.18.1
  flutter_localization: ^0.2.0
  get_storage: ^2.1.1
  google_fonts: ^6.1.0 
  mask_text_input_formatter: ^2.7.0
  flutter_launcher_icons: ^0.11.0
  image_picker: ^1.0.5
  flutter_image_compress: ^2.1.0
  fluttericon: ^2.0.0
  cached_network_image: ^3.3.1
  flutter_rating_bar: ^4.0.1
  table_calendar: ^3.0.9
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:

  uses-material-design: true

  assets:
    - assets/
 
