name: app_law_order
description: "A new Flutter project."


version: 1.0.0+5

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.6
  dio: ^5.4.0
  fluttertoast: ^8.2.4
  json_annotation: ^4.8.1
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  datetime_picker_formfield_new: ^2.1.0
  intl: ^0.18.1
  flutter_localization: ^0.2.0
  get_storage: ^2.1.1
  google_fonts: ^6.1.0 
  mask_text_input_formatter: ^2.7.0
  image_picker: ^1.0.5
  flutter_image_compress: ^2.1.0
  fluttericon: ^2.0.0
  cached_network_image: ^3.3.1
  flutter_rating_bar: ^4.0.1
  table_calendar: ^3.0.9
  flutter_custom_tabs: ^2.0.0+1
  square_progress_indicator: ^0.0.7
  socket_io_client: ^2.0.3+1
  path_provider: ^2.1.2
  open_filex: ^4.4.0
  file_picker: ^6.1.1
  loading_animation_widget: ^1.2.0+4
  currency_text_input_formatter: ^2.1.11
  flutter_native_splash: ^2.3.10
  onesignal_flutter: ^5.1.1
  change_app_package_name: ^1.1.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1

##Utilizado para gerar Icone no terminal digitar flutter pub run
# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/SIMBOLO-2.png"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon_app.png"
  remove_alpha_ios: true



flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/ca/
 
