// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAzCAw9_4I4vKMbaBdZxI4O-rVl8A8Zls',
    appId: '1:183592142336:android:73c120e601100d60cd3ae5',
    messagingSenderId: '183592142336',
    projectId: 'prestadio-5fd21',
    storageBucket: 'prestadio-5fd21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr5yA595MnbqufJj1QblIwit2MBmwdhs8',
    appId: '1:183592142336:ios:f3419a1c6fafee4bcd3ae5',
    messagingSenderId: '183592142336',
    projectId: 'prestadio-5fd21',
    storageBucket: 'prestadio-5fd21.appspot.com',
    androidClientId: '183592142336-iatrpaus527ohl7jklqron0jc3cdlbqn.apps.googleusercontent.com',
    iosClientId: '183592142336-amugpmh4k444jkfh4ik7rsqdonnv777a.apps.googleusercontent.com',
    iosBundleId: 'com.prestadioapp.prestadio',
  );
}
